### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [marsohod4you/M02mini#1]
Hello!

Could you please add information about license of this repository — is it allowed to copy, change and use code in any purpose?
It would be great to see any popular open source license.

**Comment by vazhnov** [comment]
@marsohod4you ?

**Comment by marsohod4you** [comment]
I will add..
Nick


пт, 30 окт. 2020 г. в 14:21, Alexey Vazhnov <notifications@github.com>:

**Comment by vazhnov** [comment]
If you need some help, then here is an documentation how to do it easily: [Adding a license to a repository](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository).
Or, for example, here: [How to add license to an existing GitHub project](https://stackoverflow.com/questions/31639059).

**Comment by marsohod4you** [comment]
Hope fixed.

**Comment by vazhnov** [comment]
>  Please note each subfolder has own LICENSE file based on BSD 3-Clause "New" or "Revised" License.

Great! @marsohod4you , thank you!
